name = "TopologicalSkeleton"
uuid = "fe398d12-39c6-47f6-95fa-5626f7debb32"
authors = ["Florian Gräber, Tim Pönitzsch"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
